-- SPIN XI — the daily rotation
-- Generated by scripts/build-challenges.mjs. Do not edit by hand.
--
--   546 slots · 13 objectives
--
-- Which challenge a given day gets is slot = days-since-epoch mod 546, so
-- everybody plays the same one without a calendar to keep topped up. The draw
-- itself — which squads you spin — is seeded on the day and differs every day
-- regardless, so this governs the shape of the puzzle, not its content.
--
-- 546 is lcm(7 formats, 6 presets, 13 objectives): the first day a pairing repeats.
--
-- Safe to run on its own, and safe to re-run. It replaces this one table and
-- touches nothing else, so no rating is recomputed and no nationality is
-- re-derived.

begin;

delete from challenges;

insert into challenges (slot, format, preset_id, objective, objective_desc, active)
select
  slot,
  (array['T20L', 'ODIWC', 'T20L', 'T20WC', 'T20L', 'TEST', 'ODIWC'])[slot % 7 + 1],
  (array['BALANCED', 'CLASSIC_ODI', 'BALANCED', 'PACE_BATTERY', 'BALANCED', 'AR_ARMY'])[slot % 6 + 1],
  (array['SET AND DEFEND', 'CHASE MASTER', 'GO UNBEATEN', 'LIFT THE TROPHY', 'TOP OF THE TABLE', 'NO CHOKE', 'PERFECT START', 'ON A ROLL', 'COMEBACK', 'CENTURION', 'FIVE-FOR', 'BOWLED THEM OUT', 'CRUSHING WIN'])[slot % 13 + 1],
  (array['Win 4+ matches batting first.', 'Win 5+ matches chasing a target.', 'Finish the group stage without a loss.', 'Win the final. Nothing else counts.', 'Finish the group stage in first place.', 'Reach the knockouts and lose none of them.', 'Win your first four matches.', 'Win six matches in a row.', 'Lose a match, then win the next three.', 'Have someone score a hundred in an innings.', 'Have someone take five wickets in an innings.', 'Bowl the opposition all out twice.', 'Win by 50+ runs, or with 8 wickets in hand.'])[slot % 13 + 1],
  true
from generate_series(0, 545) as slot;

-- Any client holding a cached archive must fetch the new rotation.
--
-- The version is not touched here, and must not be. It is the build id that
-- archive.sql and the static snapshot are stamped with, and it pairs the two:
-- a client whose cached copy carries that id knows it is current. Randomising
-- it on a rotation change unpairs them, so every client that ever falls back
-- to the database is told its archive is stale and reads all forty-three
-- pages again to be handed the same rows. The rotation itself is fetched live
-- on every load, so it needs no cache-busting of its own.
update dataset_meta set updated_at = now();

commit;
